# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('Last_Name', models.CharField(default=None, max_length=45)),
                ('EmailID', models.EmailField(default=None, max_length=254)),
                ('SSN', models.CharField(max_length=4)),
            ],
        ),
    ]
